FROM openjdk:8-jdk-slim
RUN useradd -m bwr
WORKDIR /home/bwr

RUN apt-get update
RUN apt-get upgrade -y

# For jar file manipulations:
RUN apt-get install -y unzip
RUN apt-get install -y zip
# For MCP:
RUN apt-get install -y python2.7
RUN apt-get install -y patch
# For hook patching:
RUN apt-get install -y libdigest-md5-perl

ARG BWR
ENV BWR=$BWR
ARG BTW
ENV BTW=$BTW
ARG MCP
ENV MCP=$MCP
ARG SVR
ENV SVR=$SVR
ARG REPO
ENV REPO=$REPO

USER bwr
COPY --chown=bwr:bwr prepare .
